import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.90
blur = true
decorations = "Buttonless"
padding = { x = 3, y = 3 }

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Light" }
bold = { style = "Medium" }
size = 13.0
offset = { x = 0, y = 3 }
