import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.90
blur = true
decorations = "Buttonless"
padding = { x = 3, y = 3 }

[font]
normal = { family = "SF Mono Square", style = "Regular" }
bold = { style = "Bold" }
size = 14.0
offset = { y = 2 }
